CREATE TABLE IF NOT EXISTS `RMSolution`.`employee` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(45) NULL,
  `marital_status` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `hire_date` DATE NULL,
  `employment_status` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NULL,
  `business_unit` VARCHAR(45) NULL,
  `division` VARCHAR(45) NULL,
  `job_family` VARCHAR(45) NULL,
  `stream` VARCHAR(45) NULL,
  `job_title` VARCHAR(45) NULL,
  `reporting_manager` INT NOT NULL DEFAULT 0,
  `retire_date` DATE NULL,
  `suspend_date` DATE NULL,
  `active_ind` TINYINT(1) NOT NULL DEFAULT 0,
  `last_degree` VARCHAR(45) NULL,
  `recruit_from` VARCHAR(255) NULL,
  `contract_expiry_date` DATE NULL,
  `last_mod_date` DATETIME NULL,
  `last_mod_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
)